baseURL = ""
title   = "Hamster wheel"

# Until we get proper taxonomies, these should be disabled
disableKinds = ['taxonomy', 'term']

staticDir = ["static"]

enableGitInfo = true
DefaultContentLanguage = "en"
enableInlineShortcodes = true
languageCode           = "en"
paginate               = 15

[Params]
author = "Johan Viklund"
